# fly.toml app configuration file generated for ecole-notre-dame-eqbsuw on 2026-04-25T21:51:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecole-notre-dame-eqbsuw'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_DEBUG = '0'
  APP_ENV = 'prod'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '15s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
