# fly.toml app configuration file generated for ecole-notre-dame-long-fire-7305 on 2026-04-25T13:15:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecole-notre-dame-long-fire-7305'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
