# fly.toml – Symfony 7 API – Ensemble Scolaire Notre-Dame Saint-Louis
# App : ecole-notre-dame-eqbsuw
# URL : https://ecole-notre-dame-eqbsuw.fly.dev

app            = 'ecole-notre-dame-eqbsuw'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV   = "prod"
  APP_DEBUG = "0"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = 'stop'
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ['app']

  [http_service.concurrency]
    type       = "requests"
    soft_limit = 200
    hard_limit = 250

[[http_service.checks]]
  grace_period = "15s"
  interval     = "30s"
  method       = "GET"
  path         = "/api/health"
  protocol     = "http"
  timeout      = "10s"

[[vm]]
  cpu_kind  = 'shared'
  cpus      = 1
  memory_mb = 256
